/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Messages sent from agent to server via stdout
 */
export type AgentToServerMessage =
  | ProcessReadyEvent
  | ProcessErrorEvent
  | ProcessStoppedEvent
  | SessionStartedEvent
  | SessionCompleteEvent
  | SessionInterruptedEvent
  | SessionErrorEvent;

/**
 * Agent process started and session is ready
 */
export interface ProcessReadyEvent {
  type: "process_ready";
  workspace: string;
  session_id: string;
  resumed?: boolean;
  forked?: boolean;
}
/**
 * Fatal error, process is stopping
 */
export interface ProcessErrorEvent {
  type: "process_error";
  message: string;
  code?: string;
}
/**
 * Agent process is stopping
 */
export interface ProcessStoppedEvent {
  type: "process_stopped";
  reason: "stop" | "error" | "eof";
}
/**
 * Message received, processing started
 */
export interface SessionStartedEvent {
  type: "session_started";
  session_id: string;
}
/**
 * Claude finished responding to the message
 */
export interface SessionCompleteEvent {
  type: "session_complete";
  session_id: string;
  result?: ResultData;
}
export interface ResultData {
  duration_ms?: number;
  duration_api_ms?: number;
  total_cost_usd?: number | null;
  num_turns?: number;
}
/**
 * Message processing was interrupted
 */
export interface SessionInterruptedEvent {
  type: "session_interrupted";
  session_id: string;
}
/**
 * Error during message processing
 */
export interface SessionErrorEvent {
  type: "session_error";
  id?: string | null;
  message: string;
  code?: string;
}
