/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Messages sent from agent to server via stdout
 */
export type AgentToServerMessage = ReadyEvent | AckEvent | CompleteEvent | InterruptedEvent | ErrorEvent | DoneEvent;

export interface ReadyEvent {
  type: "ready";
  workspace: string;
  session_id: string;
  resumed?: boolean;
  forked?: boolean;
}
export interface AckEvent {
  type: "ack";
  id: string;
}
export interface CompleteEvent {
  type: "complete";
  id: string;
  result?: ResultData;
}
export interface ResultData {
  duration_ms?: number;
  duration_api_ms?: number;
  total_cost_usd?: number | null;
  num_turns?: number;
}
export interface InterruptedEvent {
  type: "interrupted";
  id: string;
}
export interface ErrorEvent {
  type: "error";
  id?: string | null;
  message: string;
  code?: string;
}
export interface DoneEvent {
  type: "done";
  reason: "stop" | "error" | "eof";
}
