/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Messages sent from server to agent via stdin
 */
export type ServerToAgentMessage =
  | ProcessStartCommand
  | SessionMessageCommand
  | SessionInterruptCommand
  | ProcessStopCommand;
export type ContentBlock = TextContent | ImageContent;

/**
 * Start the agent process and create/resume a session
 */
export interface ProcessStartCommand {
  type: "process_start";
  /**
   * Session ID to resume, omit for new session
   */
  session_id?: string;
  /**
   * Fork the session instead of continuing it
   */
  fork?: boolean;
}
/**
 * Send a message to Claude
 */
export interface SessionMessageCommand {
  type: "session_message";
  text?: string;
  content?: ContentBlock[];
}
export interface TextContent {
  type: "text";
  text: string;
}
export interface ImageContent {
  type: "image";
  source: ImageSource;
}
export interface ImageSource {
  type: "base64" | "url";
  media_type: string;
  data: string;
}
/**
 * Interrupt the current message processing
 */
export interface SessionInterruptCommand {
  type: "session_interrupt";
}
/**
 * Stop the agent process
 */
export interface ProcessStopCommand {
  type: "process_stop";
}
