/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Messages sent from server to agent via stdin
 */
export type ServerToAgentMessage = StartCommand | MessageCommand | InterruptCommand | StopCommand;
export type ContentBlock = TextContent | ImageContent;

/**
 * Start a new session or resume an existing one
 */
export interface StartCommand {
  type: "start";
  /**
   * Session ID to resume, omit for new session
   */
  session_id?: string;
  /**
   * Fork the session instead of continuing it
   */
  fork?: boolean;
}
export interface MessageCommand {
  type: "message";
  id: string;
  text?: string;
  content?: ContentBlock[];
}
export interface TextContent {
  type: "text";
  text: string;
}
export interface ImageContent {
  type: "image";
  source: ImageSource;
}
export interface ImageSource {
  type: "base64" | "url";
  media_type: string;
  data: string;
}
export interface InterruptCommand {
  type: "interrupt";
}
export interface StopCommand {
  type: "stop";
}
