# generated by datamodel-codegen:
#   filename:  agent-to-server.json

from __future__ import annotations

from typing import Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class ProcessReadyEvent(TypedDict, closed=True):
    type: Literal['process_ready']
    workspace: str
    session_id: str
    resumed: NotRequired[bool]
    forked: NotRequired[bool]


class ProcessErrorEvent(TypedDict, closed=True):
    type: Literal['process_error']
    message: str
    code: NotRequired[str]


class SessionStartedEvent(TypedDict, closed=True):
    type: Literal['session_started']
    session_id: str


class ResultData(TypedDict, closed=True):
    duration_ms: NotRequired[float]
    duration_api_ms: NotRequired[float]
    total_cost_usd: NotRequired[float | None]
    num_turns: NotRequired[float]


class SessionCompleteEvent(TypedDict, closed=True):
    type: Literal['session_complete']
    session_id: str
    result: NotRequired[ResultData]


class SessionInterruptedEvent(TypedDict, closed=True):
    type: Literal['session_interrupted']
    session_id: str


class SessionErrorEvent(TypedDict, closed=True):
    type: Literal['session_error']
    id: NotRequired[str | None]
    message: str
    code: NotRequired[str]


class ProcessStoppedEvent(TypedDict, closed=True):
    type: Literal['process_stopped']
    reason: Literal['stop', 'error', 'eof']


AgentToServerMessage: TypeAlias = (
    ProcessReadyEvent | ProcessErrorEvent | ProcessStoppedEvent |
    SessionStartedEvent | SessionCompleteEvent | SessionInterruptedEvent | SessionErrorEvent
)
