# generated by datamodel-codegen:
#   filename:  server-to-agent.json

from __future__ import annotations

from typing import Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class ProcessStartCommand(TypedDict, closed=True):
    type: Literal['process_start']
    session_id: NotRequired[str]
    fork: NotRequired[bool]


class TextContent(TypedDict, closed=True):
    type: Literal['text']
    text: str


class ImageSource(TypedDict, closed=True):
    type: Literal['base64', 'url']
    media_type: str
    data: str


class ImageContent(TypedDict, closed=True):
    type: Literal['image']
    source: ImageSource


ContentBlock: TypeAlias = TextContent | ImageContent


class SessionMessageCommand(TypedDict, closed=True):
    type: Literal['session_message']
    text: NotRequired[str]
    content: NotRequired[list[ContentBlock]]


class SessionInterruptCommand(TypedDict, closed=True):
    type: Literal['session_interrupt']


class ProcessStopCommand(TypedDict, closed=True):
    type: Literal['process_stop']


ServerToAgentMessage: TypeAlias = (
    ProcessStartCommand | SessionMessageCommand | SessionInterruptCommand | ProcessStopCommand
)
